# Added .HostName here so your terminal tab shows it always
console_title_template = "[{{ .HostName }}] {{ .Folder }}{{ if .Root }} :: root{{ end }} :: {{ .Shell }}"
version = 3
final_space = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Path }} '
    foreground = 'blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'
    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = '{{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }}*{{ end }} <cyan>{{ if gt .Behind 0 }}⇣{{ end }}{{ if gt .Ahead 0 }}⇡{{ end }}</>'
    foreground = 'p:grey'
    background = 'transparent'
    type = 'git'
    style = 'plain'
    [blocks.segments.properties]
      branch_icon = ' '
      cache_duration = 'none'
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  # Python Venv moved here to the right side
  [[blocks.segments]]
    template = '({{ .Venv }}) '
    foreground = 'default'
    background = 'transparent'
    type = 'python'
    style = "plain"
    [blocks.segments.properties]
      home_enabled = true

  [[blocks.segments]]
    template = '{{ .FormattedMs }}'
    foreground = 'lightYellow'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'
    [blocks.segments.properties]
      cache_duration = 'none'
      threshold = 5000

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = "session"
    style = "plain"
    foreground = "blue"
    background = "transparent"
    # Removed the 'if SSH' check so it shows the hostname everywhere as requested
    template = " {{ .HostName }} "

  [[blocks.segments]]
    template = '{{if gt .Code 0}}⨘{{else}}∫{{end}}'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}lightGreen{{end}}']
    [blocks.segments.properties]
      cache_duration = 'none'
